### ISSUE TITLE
Update parameters.yml.dist (change dir volume1 to volume4)

### ISSUE THREAD

**Issue by Pyrex-FWI** [Pyrex-FWI/DeejayPoolBundle#19]
```
file_paths:
    ddp:
        provider: 1
        paths:
            - /volume4/Pool/_DigitaldjPool/
        match: '*.mp3'
    av_district:
        provider: 2
        paths:
            - /volume4/Pool/_AvDistrict/
        match: '*.mp[3|4]'
    franchise_audio:
        provider: 3
        paths:
            - /volume4/Pool/Franchise/Audio/
        match: '*.mp3'
    franchise_video:
        provider: 4
        paths:
            - /volume4/Pool/Franchise/Video/
        match: '*.mp3'
    smash:
        provider: 5
        paths:
            - /volume4/Pool/SmashVision/
        match: '*.mp4'
    sapar:
        provider: 100
        paths:
            - '/volume4/archives/-------------{ X-Tazy }-------------'
            - /volume4/archives/_Accaps
            - /volume4/archives/_Afro
            - '/volume4/archives/_Ambiance Antilles'
            - '/volume4/archives/_Ambiance fr'
            - /volume4/archives/_Azonto
            - /volume4/archives/_Biguines
            - /volume4/archives/_Bouyon
            - /volume4/archives/_Capvert
            - '/volume4/archives/_Carnaval FWI'
            - /volume4/archives/_Chanson
            - '/volume4/archives/_Classique lyrique'
            - /volume4/archives/_Club
            - '/volume4/archives/_Club 80''s'
            - /volume4/archives/_Compils
            - /volume4/archives/_Compils_Hits
            - /volume4/archives/_Country
            - /volume4/archives/_Creu
            - /volume4/archives/_Crunk
            - /volume4/archives/_Dance
            - /volume4/archives/_DanceHall
            - '/volume4/archives/_Dancehall FWI'
            - /volume4/archives/_Disco
            - /volume4/archives/_Electro
            - /volume4/archives/_FR
            - /volume4/archives/_FR_styl_90
            - /volume4/archives/_FR_style902
            - /volume4/archives/_Fiesta
            - '/volume4/archives/_Fr Doux'
            - '/volume4/archives/_Fr Vieux'
            - /volume4/archives/_Funk
            - /volume4/archives/_Games
            - /volume4/archives/_Gwo-Ka
            - '/volume4/archives/_Hard Style'
            - '/volume4/archives/_Hip Hop FWI'
            - /volume4/archives/_HipHop
            - /volume4/archives/_House
            - /volume4/archives/_Housse
            - '/volume4/archives/_Jazz Blues'
            - /volume4/archives/_Kompas
            - /volume4/archives/_Kuduro
            - /volume4/archives/_Lounge
            - /volume4/archives/_Mazurka
            - '/volume4/archives/_Meringue ok'
            - /volume4/archives/_Mixs
            - /volume4/archives/_Motown
            - /volume4/archives/_Noel
            - /volume4/archives/_OSTs
            - '/volume4/archives/_Old School'
            - '/volume4/archives/_Ols School'
            - /volume4/archives/_Pop
            - /volume4/archives/_Ragga
            - /volume4/archives/_Rai
            - /volume4/archives/_RaiNb
            - /volume4/archives/_Rap
            - '/volume4/archives/_Rap Hip Hop Fwi Underground'
            - '/volume4/archives/_Rap Us'
            - /volume4/archives/_Reaggae
            - '/volume4/archives/_Reggae Ragga'
            - /volume4/archives/_Reggaeton
            - /volume4/archives/_Rmx
            - /volume4/archives/_Rnb
            - /volume4/archives/_Rock
            - /volume4/archives/_SP
            - /volume4/archives/_Salsa
            - /volume4/archives/_Sega
            - /volume4/archives/_Serenades
            - /volume4/archives/_Slow
            - /volume4/archives/_Soca_Jump
            - '/volume4/archives/_Soiraie A blanc! SpÃ©cial de chez SpÃ©ciale'
            - /volume4/archives/_Soneries_Voices
            - /volume4/archives/_Soul
            - '/volume4/archives/_Soul - Gospel'
            - '/volume4/archives/_Underground FWI'
            - '/volume4/archives/_VariÃ©tÃ©s antillaises'
            - /volume4/archives/_Zouk
            - '/volume4/archives/_blues piano bar'
            - /volume4/archives/_breasil
            - /volume4/archives/_hiphop-KR
            - /volume4/archives/_indi
            - /volume4/archives/_instrus
            - /volume4/archives/_latin
            - /volume4/archives/_other
            - /volume4/archives/_serenade
            - /volume4/archives/_sex
            - /volume4/archives/_slam
            - /volume4/archives/_techno
            - /volume4/archives/_traditionnel
            - /volume4/archives/_trance
        match: '*.mp3'
```
